//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safecity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Safecity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;zip&quot;,&quot;lat&quot;,&quot;lng&quot;,&quot;city&quot;,&quot;state_id&quot;,&quot;state_name&quot;,&quot;zcta&quot;,&quot;parent_zcta&quot;,&quot;population&quot;,&quot;density&quot;,&quot;county_fips&quot;,&quot;county_name&quot;,&quot;county_weights&quot;,&quot;county_names_all&quot;,&quot;county_fips_all&quot;,&quot;imprecise&quot;,&quot;military&quot;,&quot;timezone&quot;
        ///&quot;00601&quot;,&quot;18.18004&quot;,&quot;-66.75218&quot;,&quot;Adjuntas&quot;,&quot;PR&quot;,&quot;Puerto Rico&quot;,&quot;TRUE&quot;,&quot;&quot;,&quot;17242&quot;,&quot;111.4&quot;,&quot;72001&quot;,&quot;Adjuntas&quot;,&quot;{&apos;72001&apos;:99.43,&apos;72141&apos;:0.57}&quot;,&quot;Adjuntas|Utuado&quot;,&quot;72001|72141&quot;,&quot;FALSE&quot;,&quot;FALSE&quot;,&quot;America/Puerto_Rico&quot;
        ///&quot;00602&quot;,&quot;18.36073&quot;,&quot;-67.17517&quot;,&quot;Aguada&quot;,&quot;PR&quot;,&quot;Puerto Rico&quot;,&quot;TRUE&quot;,&quot;&quot;,&quot;38442&quot;,&quot;523.5&quot;,&quot;72003&quot;,&quot; [rest of stri....
        /// </summary>
        public static string uszips {
            get {
                return ResourceManager.GetString("uszips", resourceCulture);
            }
        }
    }
}
